### ISSUE TITLE
No module named usb

### ISSUE THREAD

**Issue by EdwardElric64** [Qyriad/fusee-launcher#37]
When attempting to load the fusee launcher it spits out an error saying no module named USB found. I installed pyusb 1.0.2, but I'm still having the same issue...

**Comment by sabueso** [comment]
Are you using the Python3 module? Remember fusee-launcher use Python3...

**Comment by simonbh** [comment]
Install python-pyusb

**Comment by TigerC10** [comment]
I used this to move forward.

```bash
pip3 install pyusb
```

**Comment by psppwner300** [comment]
Sorry to revive this topic, but even after installing pyusb I get the following:
`Traceback (most recent call last):
  File "./fusee-launcher.py", line 593, in <module>
    switch = RCMHax(wait_for_device=arguments.wait, vid=arguments.vid, 
  File "./fusee-launcher.py", line 466, in __init__
    self.dev = self._find_device(vid, pid)
  File "./fusee-launcher.py", line 496, in _find_device
    return self.backend.find_device(vid, pid)
  File "./fusee-launcher.py", line 133, in find_device
    import usb
ModuleNotFoundError: No module named 'usb'`
